# Generated by Django 4.0.3 on 2022-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
