# Generated by Django 4.0.4 on 2022-05-11 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hyperdrated', '0003_blogpost_votes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='votes',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='voted',
            field=models.ManyToManyField(related_name='voted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
